### ISSUE TITLE
Wrong colum names after upgrading from 4.1.6 to 4.2.0 or later

### ISSUE THREAD

**Issue by fedegratti** [infused/dbf#101]
Hi @infused, I've been using this gem for 3 years without any issues (version 4.1.3). 

Now I'm upgrading my project to Rails 7.1, Ruby 3.3 and I found an issue reading my dbf file:
Almost all column names are being decoded wrongly, some characters are being added at the end of each name.

Here's a comparison table showing the column names decoded in 4.1.6 (these are correct), and the ones decoded in 4.2.0+

| Columns 4.1.6      | Columns 4.2.0+ |
| ----------- | ----------- |
| CODART      | CODARTd       |
| RUBRO      | RUBROd       |
| PROVEEDOR      | PROVEEDOR       |
| DESCR      | DESCRDOR       |
| PRECIO      | PRECIOOR       |
| MONEDA      | MONEDAOR       |
| DOLAR      | DOLAROR       |
| PRECIO2      | PRECIO2R       |
| VENTA3      | VENTA3R       |
| CAMPNUE      | CAMPNUER       |
| BPROVEED      | BPROVEED       |
| ART_PROPIO      | ART_PROPIO       |
| BBARRA      | BBARRAPIO       |
| BEQUIVA1      | BEQUIVA1O       |
| BEQUIV11      | BEQUIV11O       |
| BEQUIVA2      | BEQUIVA2O       |
| BEQUIV22      | BEQUIV22O       |
| BEQUIVA3      | BEQUIVA3O       |
| BEQUIV33      | BEQUIV33O       |
| BNOMMAR      | BNOMMARO       |

I tried all versions above 4.1.6 (4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, and 4.3.0) and I got the same issue. 

I've locked the version to 4.1.6 to keep running my app (luckily I don't need any new feature), but it would be great if there's a solution or workaround on the latest version, since 4.1.6 is quite old and I'm using Ruby 3.3 now.

Here's more information about the table:
**Table version**: 03, dBase III without memo file
**Encoding**: cp850

I can send you the dbf file if you need it. Thank you!

**Comment by infused** [comment]
Thanks for this bug report. I’m not able to replicate this behavior with any of the test files I have, but please send me the file you are having problems with I will test it out. 

Thank you,
Keith

**Comment by fedegratti** [comment]
Sure! Here's the file:
[LISTA.DBF.zip](https://github.com/infused/dbf/files/14013598/LISTA.DBF.zip)

Let me know if you need anything else.
Thank you!

**Comment by infused** [comment]
Thank you. This file helped me locate the source of the bug. I introduced this issue in 4.2.0 when doing some refactoring. The fix is included in version 4.3.1. Please give that version a try and confirm that it works for you.

**Comment by fedegratti** [comment]
It worked perfectly! thank you so much for the quick support!
