### ISSUE TITLE
SyntaxError: /usr/local/bundle/gems/dbf-4.3.1/lib/dbf/schema.rb:40: syntax error, unexpected ')'

### ISSUE THREAD

**Issue by ZeiF5quu** [infused/dbf#102]
...chema_method_name, table_only:)

tested on ruby 3.0 and rails 6.0

**Comment by ZeiF5quu** [comment]
As I can see, it caused by commit 7d3c0a0

-      send(schema_method_name, table_only)
+      send(schema_method_name, table_only:)

Mistake by autoreplacing?

**Comment by infused** [comment]
These are Ruby 3.0.x incompatible changes. I've backed them out until Ruby 3.0 hits end-of-life later this year. The fixes are included in version 4.3.2.
