### ISSUE TITLE
Possible mistake in the supported data types documentation

### ISSUE THREAD

**Issue by wolfascu** [infused/dbf#78]
In the [supported data types documentation](https://github.com/infused/dbf/blob/e482cd71e2545558a63b0cd85a49855210379c62/docs/supported_types.markdown), the data type M (Memo) seems to not be supported for Version 30 - Visual FoxPro (instead of `Y` there'a `-`).

However, using your library I successfully read a .dbf file that has been identified as vesion=30 and the corresponding .fpt and noticed that the memo field values were imported OK. Thank you for that! :smile:

So, I wondered if the docs should say that this combination is supported.

**Comment by infused** [comment]
You're correct, this was a mistake in the docs.  Thank you for pointing it out.
