### ISSUE TITLE
NoMethodError: undefined method `unpack` for nil:NilClass

### ISSUE THREAD

**Issue by bianjp** [infused/dbf#79]
I have a dbf file ([09_02_23-nqhq.dbf.zip](https://github.com/infused/dbf/files/419425/09_02_23-nqhq.dbf.zip)) which has 8687 rows, but `record_count` returns 8733. And maybe it's the cause that many methods failed.

```
filepath = '09_02_23-nqhq.dbf'
table = DBF::Table.new(filepath, nil, 'gbk')

table.record_count # works, returns 8733
table.count # error
table.each {|record| }# error
table.find 8686 # works
table.find 8687 # error
```

All errors are like the following:

```
NoMethodError: undefined method `unpack' for nil:NilClass
    from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.5/lib/dbf/table.rb:282:in `deleted_record?'
    from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.5/lib/dbf/table.rb:124:in `record'
    from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.5/lib/dbf/table.rb:113:in `block in each'
    from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.5/lib/dbf/table.rb:113:in `times'
    from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.5/lib/dbf/table.rb:113:in `each'
    from (irb):18
```

Not sure whether the dbf file is corrupted, but reading it with Python's [dbfread](https://github.com/olemb/dbfread) has no problem.

**Comment by infused** [comment]
The record count in the header of the file is incorrectly set to 8733. Possibly it was not updated correctly the last time the file was written to.  I've just released version 3.0.6 which fixes the error when trying to access the non-existent records. 

Please confirm if 3.0.6 works for you.

**Comment by bianjp** [comment]
Thanks. The former error disappeared but another error arises:

```
a.each {}
TypeError: no implicit conversion of nil into String
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/record.rb:11:in `initialize'
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/record.rb:11:in `new'
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/record.rb:11:in `initialize'
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/table.rb:125:in `new'
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/table.rb:125:in `record'
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/table.rb:113:in `block in each'
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/table.rb:113:in `times'
	from /home/vanitas/.gem/ruby/2.3/gems/dbf-3.0.6/lib/dbf/table.rb:113:in `each'
	from (irb):11
```
Is that possible to address the incorrectness of the record count and correct it automatically?

In addition, `.find` with an index greater than record count causes the same error. Maybe it's better to check the index and return nil or raise `IndexError` if the index >= record count?

**Comment by infused** [comment]
Sorry about that.  I was traveling and rushed a bad patch.  I've had to yank version 3.0.6 from rubygems due to the bad patch.  Please give 3.0.7 a try now and let me know if that fixes the issue.

**Comment by bianjp** [comment]
It works. Thanks~
Since the element may be `nil`, we have to iterate it carefully.
Remove `nil` elements (using `table.reject(&:nil?)`) before iterating may be a good idea.

But I still think that correct the record count automatically would be the best solution.
