### ISSUE TITLE
Date Parsing Issue

### ISSUE THREAD

**Issue by Mukulkaushish** [infused/dbf#82]
My expected date is  06/10/17  in column but I got  #<Date: 2017-10-06 ((2458033j,0s,0n),+0s,2299161j)>  in response...

**Comment by infused** [comment]
What type is the column a (D) Date or a (T) DateTime?

**Comment by Mukulkaushish** [comment]
its Date(D)

**Comment by infused** [comment]
dbase files represent date fields internally as 8 character strings in the format YYYYMMDD. The standard Date.parse has been used to parse that string into a Date object. There are some gems that override Date.parse, such as the american_date gem, so I've switched it to use Date.strptime(value, '%Y%m%d') which should ensure that the dates are parsed correctly. 

I've released version 3.1.1 with this change. Please give it a try and let me know if that works for you.   If it doesn't please send me a copy of the problem dbase file and I'll see if I can figure out what else might be going on.
