### ISSUE TITLE
How is the default encoding chosen?

### ISSUE THREAD

**Issue by rywall** [infused/dbf#88]
For this DBF file [Tit.dbf.zip](https://github.com/infused/dbf/files/2891452/Tit.dbf.zip) the header encoding is `nil` and I am not passing in an encoding, so I would expect the encoding to be the default encoding (UTF-8) but instead it is ASCII-8BIT. Why is this the case?

```ruby
> DBF::Table.new('Tit.dbf').encoding
=> nil
> DBF::Table.new('Tit.dbf').record(0).attributes.first.first.encoding
=> #<Encoding:ASCII-8BIT>
```

**Comment by infused** [comment]
Since a dbf file can contain binary data we open the file with 'rb' options which sets the default encoding to ASCII-8BIT.  If you know that your file is encoded as UTF-8, set the encoding when opening the file:

     DBF::Table.new('Tit.dbf', nil, 'UTF-8').encoding
     => "UTF-8"

**Comment by rywall** [comment]
Makes sense, thanks!
