### ISSUE TITLE
File causes TypeError

### ISSUE THREAD

**Issue by rywall** [infused/dbf#90]
I'm trying to read a DBF file that was included in a shapefile that I was given and it produces the following error:

```
data = File.open('Polygon.dbf')
widgets = DBF::Table.new(data)
widgets.each do |record|
  puts record.attributes
end

Traceback (most recent call last):
10: from /.rbenv/versions/2.5.7/bin/irb:11:in `<main>'
9: from (irb):9
8: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/table.rb:113:in `each'
7: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/table.rb:113:in `times'
6: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/table.rb:113:in `block in each'
5: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/table.rb:181:in `record'
4: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/table.rb:181:in `new'
3: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/record.rb:11:in `initialize'
2: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/record.rb:11:in `new'
1: from /.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/dbf-4.1.2/lib/dbf/record.rb:11:in `initialize'
TypeError (no implicit conversion of nil into String)
```

[Polygon.dbf.zip](https://github.com/infused/dbf/files/4916511/Polygon.dbf.zip)

**Comment by infused** [comment]
I'm not even sure this is a valid DBF file. It has no columns defined and though it indicates it has one record, it actually doesn't. A better approach may be to raise an error if there are no columns defined. I'm working on a patch for that now.

**Comment by infused** [comment]
As of 4.1.3 a DBF::NoColumnsDefined error will be raised when attempting to read records if no columns are defined

**Comment by rywall** [comment]
@infused great thanks! Is there a reason that you wait to raise the exception until a record is read instead of raising it when `Table` is initialized?
